[package]
name = "flag-mast-derive"
version = "0.1.0"
authors = ["toshokan <toshokan@shojigate.net>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "^1"
proc-macro-error = "^1"
syn = "^1"
quote = "^1"
